site_name: infoshare-dev-katowice
site_description: 
repo_url: https://github.com/piomin/infoshare-dev-katowice
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - infoshare-dev-katowice Documentation: index.md